version: '3'
services:
  mysql-dev:
    image: ghcr.io/mayonnaize/mysql-dev:latest
    build:
      context: ./
      dockerfile: Dockerfile
    user: user
    volumes:
      - ../:/app
    working_dir: /app
    tty: true
