version: '3'
services:
  mysql-dev:
    container_name: mysql-dev
    image: ghcr.io/mayonnaize/mysql-dev:latest
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    user: user
    volumes:
      - ../:/app
    working_dir: /app
    tty: true
    networks:
      app_net:
        ipv4_address: 172.30.0.2

  # https://mmtomitomimm.blogspot.com/2018/04/docker-mysqldb.html
  mysql-server:
    container_name: mysql-server
    # image: mysql-server
    build: ./mysql/
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      app_net:
        ipv4_address: 172.30.0.3

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.1/24
